# Generated by Django 4.0.2 on 2022-04-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedTask',
        ),
    ]
