# Generated by Django 4.0.2 on 2022-04-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtask',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='task',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='assigned_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='task_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned', to='api.task'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='assigned_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
